#!/usr/bin/env bash

echo "Downloading dependencies..."
swift build --fetch

echo "Fixing SPM bug..."

rm -rf Packages/*/Tests

echo -e '\n' >> $PWD/Packages/MySQL-0.1.14/Package.swift
echo 'let lib = Product(name: "MySQL", type: .Library(.Dynamic), modules: "MySQL"); products.append(lib)' >> $PWD/Packages/MySQL-0.1.14/Package.swift

echo -e '\n' >> $PWD/Packages/CryptoSwift-0.2.3/Package.swift
echo 'let lib = Product(name: "CryptoSwift", type: .Library(.Dynamic), modules: "CryptoSwift"); products.append(lib)' >> $PWD/Packages/CryptoSwift-0.2.3/Package.swift

cp -r $PWD/XcodeProject/SwiftGGAppServer/SHA2.swift $PWD/Packages/CryptoSwift-0.2.3/Sources/CryptoSwift

echo -e 'import PackageDescription' >> $PWD/Packages/SwiftyJSON-2.3.3/Package.swift
echo -e '\n' >> $PWD/Packages/SwiftyJSON-2.3.3/Package.swift
echo -e 'let package = Package(' >> $PWD/Packages/SwiftyJSON-2.3.3/Package.swift
echo -e '    name: "SwiftyJSON"' >> $PWD/Packages/SwiftyJSON-2.3.3/Package.swift
echo -e ')' >> $PWD/Packages/SwiftyJSON-2.3.3/Package.swift
echo -e '\n' >> $PWD/Packages/SwiftyJSON-2.3.3/Package.swift
echo 'let lib = Product(name: "SwiftyJSON", type: .Library(.Dynamic), modules: "SwiftyJSON"); products.append(lib)' >> $PWD/Packages/SwiftyJSON-2.3.3/Package.swift

echo "Fix SPM bug successful ...."
